/**
 * Build — inline SPA, then bundle Worker + DO with esbuild.
 *
 * Reads spa/index.html and generates src/spa-data.ts with the
 * HTML as a JSON-stringified constant (safe for template literals).
 * Produces dist/worker.mjs. "cloudflare:workers" is external.
 */

import * as esbuild from "esbuild";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const resolvePath = (...parts) => resolve(__dirname, ...parts);

// ── Pre-build check: canonical chat.ts ───────────────────────────────────
// Edge/src/chat.ts must be a re-export from AI/chat.ts, never a full copy.
// A full copy will drift the moment AI/chat.ts is edited. This check catches
// that before the bundle runs.

const chatTs = resolvePath("src", "chat.ts");
const chatSrc = readFileSync(chatTs, "utf8");
if (!/export \* from/.test(chatSrc)) {
  console.error(
    "ERROR: src/chat.ts is not a re-export.\n" +
    "It must be:  export * from '../../AI/chat.ts';\n" +
    "Edit AI/chat.ts — never Edge/src/chat.ts directly."
  );
  process.exit(1);
}
// Verify the canonical source exists (catch broken paths before esbuild does).
// We're in Edge/; the re-export in src/chat.ts points to ../../AI/chat.ts
// (relative to src/), but this check runs from Edge/ so the path is ../AI/chat.ts.
const canonicalFromEdge = resolvePath("..", "AI", "chat.ts");
if (!existsSync(canonicalFromEdge)) {
  console.error(`ERROR: canonical chat.ts not found at ${canonicalFromEdge} (from Edge/)`);
  process.exit(1);
}
console.log("chat.ts re-export check OK");

// ── Inline SPA ─────────────────────────────────────────────────────────

const spaPath = resolvePath("..", "Beauty", "spa", "index.html");
const spaHTML = readFileSync(spaPath, "utf8");
const spaModule = `// Auto-generated by build.js — do not edit.
export const SPA_HTML = ${JSON.stringify(spaHTML)};
`;
writeFileSync(resolvePath("src", "spa-data.ts"), spaModule);
console.log(`SPA inlined: ${spaHTML.length} bytes → src/spa-data.ts`);

// ── Bundle ─────────────────────────────────────────────────────────────

const result = await esbuild.build({
  entryPoints: [resolvePath("src", "index.ts")],
  bundle: true,
  format: "esm",
  outfile: resolvePath("dist", "worker.mjs"),
  platform: "neutral",
  external: ["cloudflare:*"],
  loader: { ".hex": "text" },
  minify: false,
  sourcemap: false,
});

if (result.errors.length > 0) {
  console.error("Build failed:", result.errors);
  process.exit(1);
}

if (result.warnings.length > 0) {
  console.warn("Build warnings:", result.warnings);
}

console.log("Build complete → dist/worker.mjs");
