// Edge/src/chat.ts — re-exports from the canonical source at AI/chat.ts.
// DO NOT EDIT THIS FILE. Edit AI/chat.ts instead.
// The Edge build (build.js) follows this re-export via esbuild bundle.
//
// If you need to add Edge-specific chat wiring (e.g. DO buffer fetching), do it
// in index.ts where the chat route lives — not here. This file stays a pure
// pass-through so the two copies can never drift.

export * from '../../AI/chat.ts';
